vim9script

## General
set number  # Show line numbers
set linebreak   # Break lines at word (requires Wrap lines)
set showbreak=+++   # Wrap-broken line prefix
set textwidth=72    # Line wrap (number of cols)
set showmatch   # Highlight matching brace
set spell   # Enable spell-checking
set visualbell  # Use visual bell (no beeping)

set hlsearch    # Highlight all search results
set smartcase   # Enable smart-case search
set ignorecase  # Always case-insensitive
set incsearch   # Searches for strings incrementally

set autoindent  # Auto-indent new lines
set cindent # Use 'C' style program indenting
set expandtab   # Use spaces instead of tabs
set shiftwidth=2    # Number of auto-indent spaces
set smartindent # Enable smart-indent
set smarttab    # Enable smart-tabs
set softtabstop=2   # Number of spaces per Tab

## Advanced
set ruler   # Show row and column ruler information

set undolevels=1000 # Number of undo levels
set backspace=indent,eol,start  # Backspace behaviour


filetype plugin indent on  # Load plugins according to detected filetype.
syntax on                  # Enable syntax highlighting.

set shiftround             # >> indents to next multiple of 'shiftwidth'.

set backspace=indent,eol,start  # Make backspace work as you would expect.
set hidden                 # Switch between buffers without having to save first.
set laststatus=2         # Always show statusline.
set display=lastline  # Show as much as possible of the last line.

set showmode               # Show current mode in command-line.
set showcmd                # Show already typed keys when more are expected.

set incsearch              # Highlight while searching with / or ?.
set hlsearch               # Keep matches highlighted.

set ttyfast                # Faster redrawing.
set lazyredraw             # Only redraw when necessary.

set splitbelow             # Open new windows below the current window.
set splitright             # Open new windows right of the current window.

set cursorline             # Find the current line quickly.
set wrapscan               # Searches wrap around end-of-file.
set report=0         # Always report changed lines.
set synmaxcol=200       # Only highlight the first 200 columns.

set list                   # Show non-printable characters.


# Put all temporary files under the same directory.
# https://github.com/mhinz/vim-galore#temporary-files
set backup
set backupdir=$HOME/.vim/files/backup/
set backupext=-vimbackup
set backupskip=
set directory=$HOME/.vim/files/swap//
set updatecount=100
set undofile
set undodir=$HOME/.vim/files/undo/
set viminfo='100,n$HOME/.vim/files/info/viminfo'

set clipboard=unnamed
set colorcolumn=80
set formatoptions+=croqlt


# for cursor
    &t_SI = "\<Esc>[6 q"
    &t_SR = "\<Esc>[4 q"
    &t_EI = "\<Esc>[2 q"


if &term =~ "xterm\\|rxvt"
    # use an orange cursor in insert mode
    &t_SI = "\<Esc>]12;orange\x7"
    # use a red cursor otherwise
    &t_EI = "\<Esc>]12;red\x7"
    silent !echo -ne "\033]12;red\007"
    # reset cursor when vim exits
    autocmd VimLeave * silent !echo -ne "\033]112\007"
    # use \003]12;gray\007 for gnome-terminal and rxvt up to version 9.21
endif


if has('multi_byte') && &encoding ==# 'utf-8'
  &listchars = 'tab:▸ ,extends:❯,precedes:❮,nbsp:±,trail:⣿'
  &fillchars = 'vert: ,diff: '  # ▚
  &showbreak = '↪ '
  highlight VertSplit ctermfg=242
  # augroup vimrc
  #   autocmd InsertEnter * set listchars-=trail:⣿
  #   autocmd InsertLeave * set listchars+=trail:⣿
  # augroup END
else
  &listchars = 'tab:> ,extends:>,precedes:<,nbsp:.'
  &fillchars = 'vert: ,stlnc:#'
  &showbreak = '-> '
  augroup vimrc
    autocmd InsertEnter * set listchars-=trail:.
    autocmd InsertLeave * set listchars+=trail:.
  augroup END
endif
