keys:
  - &users:
    - &0xjb age103r2mghf4v00ktfjmsqdvqg9s7kerg6f4zny6curayl95m5xavqsxe8md3
  - &hosts:
    - &myhost age1newtrv2uanx66emjk9cwrfwxv3usu8lge652qns2cuzn36hqtc5qca8v44
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *0xjb
      - *myhost

