[ids]
*
-3297:4976

[main]
# capslock = overload(capslock, esc)
# capslock = overload(esc, capslock)
capslock = esc

a = overloadi(a, overloadt2(meta, a, 200), 150) 
s = overloadi(s, overloadt2(alt, s, 200), 150) 
d = overloadi(d, overloadt2(shift, d, 200), 150) 
f = overloadi(f, overloadt2(control, f, 200), 150) 

; = overloadi(;, overloadt2(meta, ;, 200), 150) 
l = overloadi(l, overloadt2(alt, l, 200), 150) 
k = overloadi(k, overloadt2(shift, k, 200), 150) 
j = overloadi(j, overloadt2(control, j, 200), 150) 

g = overloadi(g, overloadt2(symb, g, 200), 150) 
h = overloadi(h, overloadt2(symb, h, 200), 150) 

v = overloadi(v, overloadt2(num, v, 200), 150) 
m = overloadi(m, overloadt2(num, m, 200), 150) 
 
[symb]
w = <
e = =
r = >
t = @
y = `
u = [
i = _
o = ]

a = \
s = (
d = -
f = )
g = +
h = %
j = {
k = ;
l = }
; = !

z = $
x = *
c = :
v = /
b = #
n = ^
m = |
, = ~
. = &


[num]
q = -
w = 5
e = 2
r = 3
t = @
u = [
o = ]

a = 7
s = .
d = 1
f = 0
g = 4
h = {
j = C
k = B
l = A
; = }

z = $
x = 6
c = 9
v = 8
b = /
n = +
m = [
, = ]
. = %
