#####################
### LOOK AND FEEL ###
#####################

# Visual styling and layout behavior
# Refer to https://wiki.hypr.land/Configuring/Variables/

# General window layout settings
# https://wiki.hypr.land/Configuring/Variables/#general
general {
    border_size = 2
    gaps_in = 0
    gaps_out = 0
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = master # Using master layout
    resize_on_border = false
    allow_tearing = false
}

# Window decorations (opacity, shadow, blur)
# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # Blur settings
    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = false
        size = 3
        passes = 1
        vibrancy = 0.1696
    }
}

# Window animations
# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = false # Animations are disabled

    # Bezier curves for animations
    # https://wiki.hypr.land/Configuring/Animations/#curves
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    # Animation rules
    # https://wiki.hypr.land/Configuring/Animations/
    animation = global,        1,     10,    default
    animation = border,        1,     5.39,  easeOutQuint
    animation = windows,       1,     4.79,  easeOutQuint
    animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    animation = windowsOut,    1,     1.49,  linear,       popin 87%
    animation = fadeIn,        1,     1.73,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear
    animation = fade,          1,     3.03,  quick
    animation = layers,        1,     3.81,  easeOutQuint
    animation = layersIn,      1,     4,     easeOutQuint, fade
    animation = layersOut,     1,     1.5,   linear,       fade
    animation = fadeLayersIn,  1,     1.79,  almostLinear
    animation = fadeLayersOut, 1,     1.39,  almostLinear
    animation = workspaces,    1,     1.94,  almostLinear, fade
    animation = workspacesIn,  1,     1.21,  almostLinear, fade
    animation = workspacesOut, 1,     1.94,  almostLinear, fade
    animation = zoomFactor,    1,     7,     quick
}

# Dwindle layout settings
# See https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    pseudotile = true
    force_split = 2
}

# Master layout settings
# See https://wiki.hypr.land/Configuring/Master-Layout/
master {
    # mfact = 0.45
    # new_status = slave
    # new_on_top = true
    # orientation = center
    slave_count_for_center_master = 0
}

# Miscellaneous settings
# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
