#################
### AUTOSTART ###
#################

# Launch necessary processes at startup
exec-once = $terminal
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = waybar
exec-once = rclone mount gdrive: ~/gdrive
exec-once = floorp
exec-once = swww-daemon
# exec-once = hyprpaper
exec-once = swaync
exec-once = nm-applet --indicator
exec-once = hypridle
exec-once = wlsunset -l 29.9 -L -95.2
exec-once = /nix/store/$(ls -d /nix/store/*polkit-gnome* | head -n 1 | xargs basename)/libexec/polkit-gnome-authentication-agent-1
