#################
### AUTOSTART ###
#################

# Launch necessary processes at startup
exec-once = $terminal
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = waybar
exec-once = rclone mount gdrive: ~/gdrive
exec-once = floorp
# exec-once = swww
# exec-once = hyprpaper
# exec-once = swaync
