#############
### INPUT ###
#############

# Keyboard and mouse/touchpad configuration
# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = altwin:meta_alt
    kb_rules =

    # repeat_delay = 250
    repeat_delay = 200
    repeat_rate = 35

    follow_mouse = 1 # Window focus follows mouse movement

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.8
    }
}

# Workspace gestures
# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Per-device configuration
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# Cursor settings
cursor {
    hide_on_key_press = true
}
