###################
### MY PROGRAMS ###
###################

# Define your default applications
# See https://wiki.hypr.land/Configuring/Keywords/
$terminal = kitty
# $fileManager = dolphin
$fileManager = nautilus
# $menu = killall rofi || rofi -show drun
$menu = ~/.config/rofi/launchers/type-2/launcher.sh || pkill rofi
$browser = floorp
$bar = pkill waybar; waybar
