# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "mdadm" ];
  boot.extraModulePackages = [ ];

# boot.initrd.services.swraid.enable = true;

boot.swraid = {
	enable = true;
	mdadmConf = ''
        ARRAY /dev/md/nixos:0 level=raid0 num-devices=2 metadata=1.2 UUID=e8749858:5fe47547:6eb7ffee:562922db devices=/dev/nvme0n1p2,/dev/nvme1n1
        MAILADDR root
      '';
};

  fileSystems."/" =
    #{ device = "/dev/disk/by-uuid/74ddff54-e7ea-4912-b41e-bbbb526182a4";
    { device = "/dev/disk/by-label/root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    #{ device = "/dev/disk/by-uuid/c9cd08f8-964e-4a08-aba6-a00f6c69c303";
    { device = "/dev/disk/by-label/boot";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/31adb93e-2d32-4455-8256-7caed9ad75ec";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/19cc334f-199e-46e8-8e3c-32cb6e8636ac"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
